version: "3"
services:

  oj-redis:
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  oj-postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

  oj-judge:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS
      # - judger_debug=1

  oj-backend:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/backend:1.6.1
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - ./data/backend:/data
      # Problem module
      - ../OnlineJudge/problem/views/admin.py:/app/problem/views/admin.py
      - ../OnlineJudge/problem/views/oj.py:/app/problem/views/oj.py
      - ../OnlineJudge/problem/urls/admin.py:/app/problem/urls/admin.py
      - ../OnlineJudge/problem/urls/oj.py:/app/problem/urls/oj.py
      - ../OnlineJudge/problem/models.py:/app/problem/models.py
      - ../OnlineJudge/problem/serializers.py:/app/problem/serializers.py
      - ../OnlineJudge/problem/migrations:/app/problem/migrations
      # Conf module
      - ../OnlineJudge/conf/views.py:/app/conf/views.py
      - ../OnlineJudge/conf/serializers.py:/app/conf/serializers.py
      - ../OnlineJudge/conf/models.py:/app/conf/models.py
      - ../OnlineJudge/conf/urls/admin.py:/app/conf/urls/admin.py
      # Utils module
      - ../OnlineJudge/utils/urls.py:/app/utils/urls.py
      - ../OnlineJudge/utils/views.py:/app/utils/views.py
      - ../OnlineJudge/utils/api/api.py:/app/utils/api/api.py
      # Account module
      - ../OnlineJudge/account/views/oj.py:/app/account/views/oj.py
      - ../OnlineJudge/account/urls/oj.py:/app/account/urls/oj.py
      # Submission module
      - ../OnlineJudge/submission/views/admin.py:/app/submission/views/admin.py
      - ../OnlineJudge/submission/views/oj.py:/app/submission/views/oj.py
      # Options
      - ../OnlineJudge/options/options.py:/app/options/options.py
      # Frontend dist
      - ../OnlineJudgeFE/dist:/app/dist
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:443:1443"
